version: 2.1

jobs:
  build:
    docker:
      - image: cimg/base:stable
    resource_class: small
    steps:
      - checkout
      - run: echo "hello from service-a"

  report-status:
    docker: 
      - image: cimg/base:2021.11
    resource_class: small
    steps:
      - run:
          name: Report status back to main pipeline
          command: |
            curl --request POST \
              --url https://circleci.com/api/v2/project/gh/jenny-miggin/multi-repo-demo/pipeline \
              --header "Circle-Token: $CIRCLE_API_TOKEN" \
              --header "content-type: application/json" \
              --data '{"branch":"main","parameters":{"service-name":"$CIRCLE_PROJECT_REPONAME", status:"successful" }}'
          when: on_success
workflows:
  run-jobs:
    jobs:
      - build
      - report-status:
          requires:
            - build
          context:
            - cci